[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0"
actix-files = "0.6"
reqwest = {version = "0.12.5", features = ["blocking", "json"]}
thiserror = "1.0"
env_logger = "0.11.5"
log = "0.4"
async-trait = "0.1.81"